constants:
  file:
    directory: D:\BJG\backend\upload

spring:
  application:
    name: gallery
  datasource:
    url: jdbc:mariadb://localhost/gallery
    username: root
    password: green502
  servlet:
    multipart:
      max-file-size: 15MB

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: mappers/**/*.xml
